### ISSUE TITLE
Missing VectorResult return type on query

### ISSUE THREAD

**Issue by boarush** [turbopuffer/turbopuffer-python#4]
In `namespace.py`, the `query` function overloads have no return type defined as shown below.

```python
@overload
def query(self,
          vector: Optional[List[float]] = None,
          distance_metric: Optional[str] = None,
          top_k: int = 10,
          include_vectors: bool = False,
          include_attributes: Optional[List[str]] = None,
          filters: Optional[Dict[str, List[FilterTuple]]] = None):
    ...

@overload
def query(self, query_data: VectorQuery):
    ...

@overload
def query(self, query_data: dict):
    ...

def query(self,
          query_data = None,
          vector = None,
          distance_metric = None,
          top_k = None,
          include_vectors = None,
          include_attributes = None,
          filters = None) -> VectorResult:
```

It would be better if the overloaded functions also have the return type defined to have better type safety.

Also, `VectorResult` class is not imported currently in `__init__.py`. Is there a reason for it? It would be better to have that type available as well.

**Comment by boarush** [comment]
I have created a PR to add return types and also export `VectorResult` -> #5

**Comment by xthexder** [comment]
This change went out as part of the [0.1.3 version release](https://pypi.org/project/turbopuffer/0.1.3/).
Lets us know if you run into anything else while using turbopuffer!
